# Generated by Django 2.2.1 on 2019-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=600)),
                ('last_name', models.CharField(max_length=600)),
                ('address', models.CharField(max_length=700)),
                ('city', models.CharField(max_length=600)),
                ('payment_method', models.CharField(max_length=600)),
                ('payment_data', models.CharField(max_length=600)),
                ('items', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('imagelink', models.CharField(max_length=800)),
            ],
        ),
    ]
